- name: Configure Aruba Switch
  hosts: aruba_switch
  gather_facts: no
  tasks:
    - name: Send CLI commands to Aruba switch
      aoscx_command:
        commands:
          - interface 1/1/1
          - description "Configured by Ansible"
          - exit
        provider:
          host: "{{ inventory_hostname }}"
          username: "{{ ansible_user }}"
          password: "{{ ansible_password }}"
          transport: cli
